### ISSUE TITLE
Support Knative eventing in vHive

### ISSUE THREAD

**Issue by ustiugov** [ease-lab/vhive#164]

**Comment by shyamjesal** [comment]
Source: [https://knative.dev/docs/eventing/accessing-traces/](https://knative.dev/docs/eventing/accessing-traces/)

The following demonstrates how to trace requests in Knative Eventing with Zipkin, using the [`TestBrokerTracing`](https://github.com/knative/eventing/blob/master/test/conformance/broker_tracing_test.go) End-to-End test.\
For this example, assume the following details:

-   Everything happens in the `includes-incoming-trace-id-2qszn` namespace.
-   The Broker is named `br`.
-   There are two Triggers that are associated with the Broker:

    -   `transformer` - Filters to only allow events whose type is `transformer`. Sends the event to the Kubernetes Service `transformer`, which will reply with an identical event, except the replied event's type will be `logger`.
    -   `logger` - Filters to only allow events whose type is `logger`. Sends the event to the Kubernetes Service `logger`.

-   An event is sent to the Broker with the type `transformer`, by the Pod named `sender`.

Given the above, the expected path and behavior of an event is as follows:

1.  `sender` Pod sends the request to the Broker.
2.  Go to the Broker's ingress Pod.
3.  Go to the `imc-dispatcher` Channel (imc stands for InMemoryChannel).
4.  Go to both Triggers.

    1.  Go to the Broker's filter Pod for the Trigger `logger`. The Trigger's filter ignores this event.

    1.  Go to the Broker's filter Pod for the Trigger `transformer`. The filter does pass, so it goes to the Kubernetes Service pointed at, also named `transformer`.

        1.  `transformer` Pod replies with the modified event.
        2.  Go to an InMemory dispatcher.
        3.  Go to the Broker's ingress Pod.
        4.  Go to the InMemory dispatcher.

        1.  Go to both Triggers.

            1.  Go to the Broker's filter Pod for the Trigger `transformer`. The Trigger's filter ignores the event.

            1.  Go to the Broker's filter Pod for the Trigger `logger`. The filter passes.

                1.  Go to the `logger` Pod. There is no reply.

This is a screenshot of the trace view in Zipkin. All the red letters have been added to the screenshot and correspond to the expectations earlier in this section:  
![image](https://user-images.githubusercontent.com/20225226/111162952-a8f96b80-85c2-11eb-8e9d-26a85213fbd0.png)
