### ISSUE TITLE
Deploy and populate a local container registry

### ISSUE THREAD

**Issue by ustiugov** [ease-lab/vhive#165]
For the FaaS benchmarking at scale, we would like to avoid the obvious bottleneck of a remote registry, like DockerHub. 

Required changes:

- [ ] the ctriface module should not default to `docker.io/`
- [ ] YAML files should specify the registry when specifying each container image
- [ ] need to add a script that would deploy by URL and populate the local registry in a vHive cluster, by copying the images from remote registries, e.g., DockerHub, to the cluster-local registry
- [ ] tests need to be updated accordingly

We welcome a contribution from @amohoste on this issue.

**Comment by amohoste** [comment]
How would you like the local registry population to work? Do you want it to be automated such that upon calling the deployer, images are first pulled to the local registry or did you have a separate script in mind. Also, there should be a way for the script to know which global registry it can fetch the images from. A straightforward way to do this would be to map the local url to the global url of a specified registry. For example if a user enters `docker-registry.registry.svc.cluster.local:5000/vhiveease/pyaes:var_workload` in the yaml file, the script tries to pull the image from `docker.io/vhiveease/pyaes:var_workload`.

Please feel free to give other suggestions.

**Comment by ustiugov** [comment]
@amohoste sorry for the late response. 

I would prefer to give complete flexibility of using different registries, incl. dockerhub, AWS ecr, vHive local registry, etc.,  to the user who specifies the YAML files. The script can take a list of images and two arguments: source registry and destination registry.

**Comment by amohoste** [comment]
Okay, I suppose it should be in a separate script it is then?

Regarding the testcases, should I make them point to docker.io and add some for the local registry or should I port all of them to the local registry?

**Comment by ustiugov** [comment]
yes, separate. In the unit tests as well as the integration tests except in the `cri/` module, you can use `docker.io`. In `cri`, we test integration with kubernetes so there it would be good to use the local registry instead (e.g., for one of the functions). The CRI tests are not 100% stable as of now so please let us know in case of any weird failures.

**Comment by amohoste** [comment]
Could you point me to where the test images for the CRI tests get deployed? `cri_test.go` is calling the following hardcoded url: `helloworld.default.192.168.1.240.xip.io:80` but I'm not 100% sure where this is getting deployed exactly. If we would want to test a function deployed from the local registry, I think we also would also need to deploy a different image than helloworld since we can't have 2 images with the same name.

**Comment by ustiugov** [comment]
@amohoste these are three different entities. 
* `helloworld.default.192.168.1.240.xip.io:80` is a URL of a deployed function that is exposed by the ingress (i.e., istio load balancer).
* Images are root filesystems (think of docker images). 
* The registry is just a database of these images that need to be pulled by workers (hosts) before starting function instances. 

Different functions can use the same images the same way as you can spawn many instances of docker containers on one or different nodes.

**Comment by amohoste** [comment]
I am indeed aware of this distinction I was assuming the helloworld part in the deployed function url was derived from the imagename which would mean that deploying the same image twice from different registries wouldn’t work because it would result in the same url. It indeed makes sense that’s it’s possible to be able to specify the name of the deployed function url.

Regarding the other part of my question, where do the functions for the tests deployed exactly. I would also have to pull am image to the local registry and deploy it if I would want to test the local registry functions in the CRI module.

**Comment by ustiugov** [comment]
Functions deployment is cluster-wide. k8s decides when and on which host to starts an instance of a function. During deployment, it spawns one instance, by default. k8s decides on the worker placement, then the worker fetches the image from the given registry and stores the image locally in the devmapper (think of `docker pull`). A user doesn't need to do anything except specify a registry -- that must be reachable from a service within the vHive cluster or over the Internet-- as a part of the image name in the corresponding YAML.

**Comment by amohoste** [comment]
Sorry, I should have made my question more clear. I meant to say in which part of the testing code the deployment of the functions is being done. I saw the [github workflow](https://github.com/ease-lab/vhive/blob/master/.github/workflows/cri_tests.yml#L83) contains some code to deploy the functions but the [makefile](https://github.com/ease-lab/vhive/blob/master/cri/Makefile#L39) also contains some deployment functionality. Is it sufficient to pull the image to a local registry and deploy it in the makefile?

**Comment by ustiugov** [comment]
you are looking at the wrong test (the one for the stock knative mode). For the vHive default mode with Firecracker, look at this [test](https://github.com/ease-lab/vhive/blob/ae68cf63218b47c83e3fd34a0c751edced007c65/.github/workflows/cri_tests.yml#L21). You can augment this test.
