### ISSUE TITLE
Deploying functions fails in vanilla snapshot mode when I restart vHive

### ISSUE THREAD

**Issue by sosson97** [ease-lab/vhive#215]
**Describe the bug**
I'm testing vHive in firecracker's vanilla snapshot mode(gives `-snapshots` option to vHive) on single node container environment described in [this](https://github.com/ease-lab/vhive/blob/main/docs/developers_guide.md#deploying-single-node-container-environment). The example [deployer](https://github.com/ease-lab/vhive/blob/main/examples/deployer/client.go) works like a charm when I use it right after the one node cluster setup. However, when I clean-up and restart vHive on the same container, the deployer stops and vHive keeps printing error messages . This error occurs even after restarting container, so I should delete the old container and setup the new one every time I change vHive options.

See Logs for detailed error message. 

**To Reproduce**
1. Setup a single node container environment following [this](https://github.com/ease-lab/vhive/blob/main/docs/developers_guide.md#deploying-single-node-container-environment).
2. Setup a single node vHive cluster following the [manual](https://github.com/ease-lab/vhive/blob/main/docs/quickstart_guide.md#manual). Run `sudo ./vhive -snapshtos` instead of `sudo ./vhive` to enable the vanilla snapshot mode.
3. Run ./example/deployer/client.go.
4. Close vHive and run ./scripts/cluster/create_one_node_cluster.sh for clean-up. 
5. Repeat 2-3. Deployer will fail. 

**Expected behavior**
Deploying should work as usual. 

**Logs**
vHive

```
ERRO[2021-04-16T11:26:31.810795364Z] VM config for pod 3627beec6cd01e86d69f29a46c392fbe2d64d3486ed143b3a83f6397e4dd931a does not exist
ERRO[2021-04-16T11:26:31.810827838Z]                                               error="VM config for pod does not exist"
ERRO[2021-04-16T11:26:48.347416573Z] coordinator failed to start VM                error="Failed to get/pull image: unpack: failed to prepare extraction snapshot \"extract-296313985-FSM8 sha256:cd7100a72410606589a54b932cabd804a17f9ae5b42a1882bd56d263e02b6215\": failed to save metadata for device \"a2ac767286750bf72628300cfb679e798f4443ad42cc7a2194e266e4906d4837_thinpool-snap-14\" (parent: \"\"): object already exists: unknown" image="vhiveease/rnn_serving:var_workload" vmID=55
ERRO[2021-04-16T11:26:48.347488813Z] failed to start VM                            error="Failed to get/pull image: unpack: failed to prepare extraction snapshot \"extract-296313985-FSM8 sha256:cd7100a72410606589a54b932cabd804a17f9ae5b42a1882bd56d263e02b6215\": failed to save metadata for device \"a2ac767286750bf72628300cfb679e798f4443ad42cc7a2194e266e4906d4837_thinpool-snap-14\" (parent: \"\"): object already exists: unknown"
ERRO[2021-04-16T11:26:48.350721293Z] VM config for pod 3627beec6cd01e86d69f29a46c392fbe2d64d3486ed143b3a83f6397e4dd931a does not exist
ERRO[2021-04-16T11:26:48.350764266Z]                                               error="VM config for pod does not exist"
```

firecracker-containerd
```
DEBU[2021-04-16T11:26:48.296965537Z] creating new thin device 'a2ac767286750bf72628300cfb679e798f4443ad42cc7a2194e266e4906d4837_thinpool-snap-14'
ERRO[2021-04-16T11:26:48.297051243Z] failed to create thin device for snapshot 14  error="failed to save metadata for device \"a2ac767286750bf72628300cfb679e798f4443ad42cc7a2194e266e4906d4837_thinpool-snap-14\" (parent: \"\"): object already exists"
DEBU[2021-04-16T11:26:48.297089840Z] snapshotter error                             error="1 error occurred:\n\t* failed to save metadata for device \"a2ac767286750bf72628300cfb679e798f4443ad42cc7a2194e266e4906d4837_thinpool-snap-14\" (parent: \"\"): object already exists\n\n"
DEBU[2021-04-16T11:26:48.304656470Z] garbage collected                             d="599.868µs"```

**Comment by ustiugov** [comment]
@sosson97 thank you for reporting the issue. It seems to be connected to the devmapper pool of images... This thin pool should be deleted and re-created by `./scripts/cluster/create_one_node_cluster.sh` but it seems to be not working. 

@shyamjesal any thoughts?

The workaround is to delete the `kind` cluster and restart it, as described here.
