### ISSUE TITLE
Create single module, aggregate dependencies

### ISSUE THREAD

**Issue by plamenmpetrov** [ease-lab/vhive#263]
Currently, we have many modules, for which we have `go.mod`s, where the dependencies for each module are kept. This make upgrading some dependencies such as firecracker-containerd error prone, because the dependency needs to be changed in several places.

It seems a lot of the dependencies overlap across the modules - containerd, firecracker-containerd, and some less obvious ones, like grpc. This is one reason why I propose to keep the non-top modules as packages - `misc`, `taps`, etc. Another reason is that really these modules are not meant to be used outside of vHive in order to warrant keeping them as modules if someone wants to use them.

I propose the following way to do this:
1. Delete `go.mod` and `go.sum` in all modules we want to keep as packages. Import paths should stay the same.
2. Introduce the missing dependencies with version to the top-level `go.mod`.

**Comment by ustiugov** [comment]
[example](https://github.com/ease-lab/vhive-bench/tree/main/src)

**Comment by boramalper** [comment]
I'll try to tackle this. Currently there are 13 modules:
```bash
$ find . -name "go.mod"
./go.mod
./misc/go.mod
./examples/protobuf/helloworld/go.mod
./examples/knative-eventing-tutorial/go.mod
./cri/go.mod
./metrics/go.mod
./ctriface/go.mod
./memory/manager/go.mod
./proto/go.mod
./function-images/tests/save_load_minio/server/go.mod
./function-images/tests/save_load_minio/client/go.mod
./function-images/tests/save_load_minio/proto_gen/go.mod
./taps/go.mod
```

and you want a single module residing at the root of the repository except for `examples` and `function-images`, i.e.:

```bash
$ find . -name "go.mod"
./go.mod
./examples/protobuf/helloworld/go.mod
./examples/knative-eventing-tutorial/go.mod
./function-images/tests/save_load_minio/server/go.mod
./function-images/tests/save_load_minio/client/go.mod
./function-images/tests/save_load_minio/proto_gen/go.mod
```

Right?

**Comment by ustiugov** [comment]
let's ignore `./function-images` and `examples/` folders. all others need to be deleted
