### ISSUE TITLE
"CI/CD for base images / Deploy vhiveease/golang" Always Fails at docker login

### ISSUE THREAD

**Issue by boramalper** [ease-lab/vhive#276]
**Describe the bug**
"CI/CD for base images / Deploy vhiveease/golang" always fails at docker login with the following error:

```
Error: Username and password required
```

**To Reproduce**
@MBaczun I presume [it works in your PRs](https://github.com/ease-lab/vhive/pull/250) because you have added the secrets to your own profile rather than ease-lab's?

**Expected behavior**
It should work for everyone

**Logs**
See https://github.com/ease-lab/vhive/pull/275/checks?check_run_id=2787627779 as an arbitrary example.

**Comment by MBaczun** [comment]
Hi Bora, I did not add the secrets myself, I asked @ustiugov to add them and they were added very recently :). This is definitely an issue with the secrets though, hopefully Dmitrii has more insight

**Comment by MBaczun** [comment]
Upon further investigation the workflow also works on the main branch. Could you try rebasing your fork again to see if that makes a difference?

**Comment by ustiugov** [comment]
@boramalper the secrets are deployed for ease-lab organization. probably, your fork does not relate to it. you can go to our dockerhub account and create similar secrets for your account.
