### ISSUE TITLE
CD should only be performed if integration test pass (CI)

### ISSUE THREAD

**Issue by ustiugov** [ease-lab/vhive#282]
This [workflow](https://github.com/ease-lab/vhive/blob/c5e706ac31eeb7ae7f0267202c7b28e020cbdf7d/.github/workflows/image_build.yml#L1) must be triggered **only** when the [composition tests](https://github.com/ease-lab/vhive/blob/main/.github/workflows/function-composition.yml) finish successfully otherwise we risk pushing Docker images that don't pass our tests. 

The way to do this is using [workflow_run](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run). 

This is not a high priority but need to be done this week before we have started to bring up real workloads.

**Comment by MBaczun** [comment]
Addressed in #283
