### ISSUE TITLE
[zipkin] Need to export Zipkin port from the kind container to the host

### ISSUE THREAD

**Issue by ustiugov** [ease-lab/vhive#297]
This is required when visualizing traces from a cluster running inside KinD.

@shyamjesal I guess this should be patched by a simple addition to our KinD container image, what do you think? 

This has a relatively low priority but can be very useful as people start bringing up new workloads.

Reported by @MBaczun

**Comment by shyamjesal** [comment]
Yes, this is possible using a simple kind [config variable](https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings).

**Comment by ustiugov** [comment]
@shyamjesal cool, can you do that this week?

**Comment by ustiugov** [comment]
closing due to its low priority
