### ISSUE TITLE
Invoker missing output

### ISSUE THREAD

**Issue by MBaczun** [ease-lab/vhive#305]
**Describe the bug**
The invoker produces a wrong number of output latency measurements. This is most apparent when I tried to use the invoker to invoke both the eventing and serving benchmarks at the same time. With rps=1 and time=5 only 4 entries were made into the output csv.

There is also a discrepancy between the number of zipkin traces emitted and the number of latencies recorded. E.g. with rps=1 and time=5 and invoking only the serving benchmark, the invoker emits 6 traces but still only 4 latencies are recorded.

**To Reproduce**
(on cloudlab) Run the invoker and cat the csv file. Deploy and use one or both of the benchmarks as necessary (if using both, it's easier to deploy serving first and eventing second to save having to change the namespace manually).

**Expected behavior**
The number of output latencies should match the input parameters. With rps=1 and time=5 and two input function URLs I would expect 10 output latency readings.

**Comment by ustiugov** [comment]
Must not be a bug in the functionality but let's keep it open. Need to do the following:

- [ ] clarify that RPS is total not per function
- [ ] compare the performance of Serving vs Eventing.

**Comment by boramalper** [comment]
I believe this is fixed by #331?
