### ISSUE TITLE
Stale getting started guide with missing folders

### ISSUE THREAD

**Issue by cvetkovic** [ease-lab/vhive#401]
I tried to set up and run vHive unsuccessfully, according to the instructions in the Getting Started guide (https://github.com/ease-lab/vhive/blob/main/docs/quickstart_guide.md), but I believe the document is stale. Concretely, while executing commands from IV.2 section some of the dependencies cannot be fetched as they are missing from either vHive or third-party repositories. Please have a look at the attachment to see which ones concretely.
![Screenshot from 2021-09-21 12-37-03](https://user-images.githubusercontent.com/16463659/134159694-a5b3d3cc-2726-45b0-a8f0-7842aad67302.png)

The setup on which I tried to run vHive is as a new CloudLab instance, as described in the aforementioned guide.

**Comment by ustiugov** [comment]
docs fixed by #397
