### ISSUE TITLE
Quick start guide commands for profiling produces an error

### ISSUE THREAD

**Issue by leonardvaney** [ease-lab/vhive#443]
When executing the first example function from the profiling.md file, an error occurs when creating the containerd client. 

What I did before triggering the bug:
- Install a node with the 4 first steps of the [quick start guide](https://github.com/ease-lab/vhive/blob/main/docs/quickstart_guide.md)
- Install pmu-tools with the fix proposed in this [issue](https://github.com/andikleen/pmu-tools/issues/408#issue-1065941426)
- Run the following command : `sudo env "PATH=$PATH" go test -v -timeout 99999s -run TestProfileSingleConfiguration \
-args -funcNames helloworld -vm 1 -rps 20 -l 1`

Here are the logs that show up when executing the function:
```
INFO[2021-12-02T09:47:05.497626118-07:00] Orchestrator snapshots enabled: false        
INFO[2021-12-02T09:47:05.497714308-07:00] Orchestrator UPF enabled: false              
INFO[2021-12-02T09:47:05.497737585-07:00] Orchestrator lazy serving mode enabled: false 
INFO[2021-12-02T09:47:05.497752638-07:00] Orchestrator UPF metrics enabled: false      
INFO[2021-12-02T09:47:05.497767528-07:00] Drop cache: true                             
INFO[2021-12-02T09:47:05.497782085-07:00] Bench dir: bench_results                     
INFO[2021-12-02T09:47:05.497798920-07:00] Registering bridges for tap manager          
INFO[2021-12-02T09:47:05.499657081-07:00] Creating containerd client                   
FATA[2021-12-02T09:47:15.500626224-07:00] Failed to start containerd clientfailed to dial "/run/firecracker-containerd/containerd.sock": context deadline exceeded 
exit status 1
FAIL	github.com/ease-lab/vhive	10.017s

```
This was done on a cloudlab cluster with the vhive-ubuntu20 profile and with the 1.4.1 release of vhive.

Don't hesitate to ask me more info about this issue.

**Comment by ustiugov** [comment]
sorry for the late response. please follow the updated manual.
