### ISSUE TITLE
Kubelet "isn't running or healthy." for single node setup

### ISSUE THREAD

**Issue by rjclemens** [ease-lab/vhive#492]
**Describe the bug**
Kubelet "isn't running or healthy." when trying to run the single node cluster script.

**To Reproduce**
Follow step (II) section 1: "Setup all nodes", then follow step (III):  Setup a Single-Node Cluster; getting Kubelet errors on part 6, running the single node cluster script. 

**Expected behavior**
Expected the script to execute successfully without errors

**Logs**
`
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.

	Unfortunately, an error has occurred:
		timed out waiting for the condition

	This error is likely caused by:
		- The kubelet is not running
		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

	If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
		- 'systemctl status kubelet'
		- 'journalctl -xeu kubelet'

	Additionally, a control plane component may have crashed or exited when started by the container runtime.
	To troubleshoot, list all containers using your preferred container runtimes CLI.

	Here is one example how you may list all Kubernetes containers running in cri-o/containerd using crictl:
		- 'crictl --runtime-endpoint /etc/vhive-cri/vhive-cri.sock ps -a | grep kube | grep -v pause'
		Once you have found the failing container, you can inspect its logs with:
		- 'crictl --runtime-endpoint /etc/vhive-cri/vhive-cri.sock logs CONTAINERID'

error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
+ mkdir -p /home/rjc422/.kube
+ sudo cp -i /etc/kubernetes/admin.conf /home/rjc422/.kube/config
cp: overwrite '/home/rjc422/.kube/config'? yes
++ id -u
++ id -g
+ sudo chown 1567675:1580621 /home/rjc422/.kube/config
+ '[' 1567675 -eq 0 ']'
+ kubectl taint nodes --all node-role.kubernetes.io/master-
The connection to the server 128.253.128.69:xxxx was refused - did you specify the right host or port?
+ /home/rjc422/vhive/scripts/cluster/setup_master_node.sh
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
The connection to the server 128.253.128.69:xxxx was refused - did you specify the right host or port?
The connection to the server 128.253.128.69:xxxx was refused - did you specify the right host or port?
The connection to the server 128.253.128.69:xxxx was refused - did you specify the right host or port?
The connection to the server 128.253.128.69:xxxx was refused - did you specify the right host or port?
The connection to the server 128.253.128.69:xxxx was refused - did you specify the right host or port?
The connection to the server 128.253.128.69:xxxx was refused - did you specify the right host or port?
The connection to the server 128.253.128.69:xxxx was refused - did you specify the right host or port?
`
**Notes**
One of our error logs indicated that "The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)." In the file vhive/configs/firecracker-containerd/config.toml we commented out the first line (disabled_plugins = ["cri"]) to see if it was causing us the error; we ended up with the same error logs.

**Comment by ustiugov** [comment]
@rjclemens thank you for the detailed issue. Could you please specify:
- on which node you ran it (hardware, host OS)
- is it a sporadic error? does it reproduce?

**Comment by ustiugov** [comment]
@rjclemens is the issue still relevant?

**Comment by rjclemens** [comment]
Hi, sorry, this issue is no longer relevant, we were able to get it running. Thank you!

**Comment by Prithvi-Velicheti** [comment]
@rjclemens how did you resolve this ? Did you manupulate the cgroup configuration ?
