### ISSUE TITLE
Function Deployment Failed: helloworld:var_workload pull failed

### ISSUE THREAD

**Issue by catchabhisek** [ease-lab/vhive#504]
Hi,

I am trying to run the deployer script after Vhive installation, However, the helloworld pod is getting CreateContainerError. While further troubleshooting the issue, I have found that it is unable to pull https://ghcr.io/v2/ease-lab/helloworld/manifests/var_workload. Yet, I was able to create a pod with that image. I am attaching the kubectl describe pods result below. Would you please help me with the issue.

`Name:         helloworld-0-00001-deployment-66777f4bb5-tnj5s
Namespace:    default
Priority:     0
Node:         awsum/192.168.122.60
Start Time:   Fri, 18 Mar 2022 17:50:29 +0000
Labels:       app=helloworld-0-00001
              pod-template-hash=66777f4bb5
              serving.knative.dev/configuration=helloworld-0
              serving.knative.dev/configurationGeneration=1
              serving.knative.dev/configurationUID=f3d550b9-95ee-43c4-8867-f5e006b0c123
              serving.knative.dev/revision=helloworld-0-00001
              serving.knative.dev/revisionUID=8af2a280-84d9-4970-a8fb-2b0c6a2810ba
              serving.knative.dev/service=helloworld-0
              serving.knative.dev/serviceUID=e90cc8e4-45c9-4ce9-90e3-5e21aec2c33e
Annotations:  autoscaling.knative.dev/target: 1
              cni.projectcalico.org/podIP: 192.168.0.97/32
              cni.projectcalico.org/podIPs: 192.168.0.97/32
Status:       Pending
IP:           192.168.0.97
IPs:
  IP:           192.168.0.97
Controlled By:  ReplicaSet/helloworld-0-00001-deployment-66777f4bb5
Containers:
  user-container:
    Container ID:   containerd://dc30b6e15a807af8a096169e9e7ff95db4847fc57c83e8228a5a6f8f2fc91ee1
    Image:          crccheck/hello-world:latest
    Image ID:       docker.io/crccheck/hello-world@sha256:0404ca69b522f8629d7d4e9034a7afe0300b713354e8bf12ec9657581cf59400
    Port:           50051/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CreateContainerError
    Last State:     Terminated
      Exit Code:    0
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  10
    Environment:
      GUEST_PORT:       50051
      GUEST_IMAGE:      ghcr.io/ease-lab/helloworld:var_workload
      http_proxy:       http://10.10.78.61:3128
      https_proxy:      http://10.10.78.61:3128
      PORT:             50051
      K_REVISION:       helloworld-0-00001
      K_CONFIGURATION:  helloworld-0
      K_SERVICE:        helloworld-0
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5nhpj (ro)
  queue-proxy:
    Container ID:   
    Image:          docker.io/hyhe/queue-39be6f1d08a095bd076a71d288d295b6@sha256:e78d4bfc0710ba603bb64aacb2e98aa26d4674a94b67d4633edf4e580725d3aa
    Image ID:       
    Ports:          8022/TCP, 9090/TCP, 9091/TCP, 8013/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP
    State:          Waiting
      Reason:       CreateContainerError
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      25m
    Readiness:  http-get http://:8013/ delay=0s timeout=1s period=1s #success=1 #failure=3
    Environment:
      SERVING_NAMESPACE:                 default
      SERVING_SERVICE:                   helloworld-0
      SERVING_CONFIGURATION:             helloworld-0
      SERVING_REVISION:                  helloworld-0-00001
      QUEUE_SERVING_PORT:                8013
      CONTAINER_CONCURRENCY:             0
      REVISION_TIMEOUT_SECONDS:          300
      SERVING_POD:                       helloworld-0-00001-deployment-66777f4bb5-tnj5s (v1:metadata.name)
      SERVING_POD_IP:                     (v1:status.podIP)
      SERVING_LOGGING_CONFIG:            
      SERVING_LOGGING_LEVEL:             
      SERVING_REQUEST_LOG_TEMPLATE:      {"httpRequest": {"requestMethod": "{{.Request.Method}}", "requestUrl": "{{js .Request.RequestURI}}", "requestSize": "{{.Request.ContentLength}}", "status": {{.Response.Code}}, "responseSize": "{{.Response.Size}}", "userAgent": "{{js .Request.UserAgent}}", "remoteIp": "{{js .Request.RemoteAddr}}", "serverIp": "{{.Revision.PodIP}}", "referer": "{{js .Request.Referer}}", "latency": "{{.Response.Latency}}s", "protocol": "{{.Request.Proto}}"}, "traceId": "{{index .Request.Header "X-B3-Traceid"}}"}
      SERVING_ENABLE_REQUEST_LOG:        false
      SERVING_REQUEST_METRICS_BACKEND:   prometheus
      TRACING_CONFIG_BACKEND:            none
      TRACING_CONFIG_ZIPKIN_ENDPOINT:    
      TRACING_CONFIG_DEBUG:              false
      TRACING_CONFIG_SAMPLE_RATE:        0.1
      USER_PORT:                         50051
      SYSTEM_NAMESPACE:                  knative-serving
      METRICS_DOMAIN:                    knative.dev/internal/serving
      SERVING_READINESS_PROBE:           {"tcpSocket":{"port":50051,"host":"127.0.0.1"},"successThreshold":1}
      ENABLE_PROFILING:                  false
      SERVING_ENABLE_PROBE_REQUEST_LOG:  false
      METRICS_COLLECTOR_ADDRESS:         
      CONCURRENCY_STATE_ENDPOINT:        
      CONCURRENCY_STATE_TOKEN_PATH:      /var/run/secrets/tokens/state-token
      HOST_IP:                            (v1:status.hostIP)
      ENABLE_HTTP2_AUTO_DETECTION:       false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5nhpj (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-5nhpj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-5nhpj
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  6m44s                  default-scheduler  Successfully assigned default/helloworld-0-00001-deployment-66777f4bb5-tnj5s to awsum
  Normal   Pulled     6m36s                  kubelet            Successfully pulled image "crccheck/hello-world:latest" in 6.586890048s
  Normal   Pulled     6m3s                   kubelet            Successfully pulled image "crccheck/hello-world:latest" in 2.369211495s
  Normal   Pulled     5m29s                  kubelet            Successfully pulled image "crccheck/hello-world:latest" in 2.419226594s
  Normal   Pulled     4m55s                  kubelet            Successfully pulled image "crccheck/hello-world:latest" in 3.111797422s
  Normal   Pulling    4m24s (x5 over 6m43s)  kubelet            Pulling image "crccheck/hello-world:latest"
  Normal   Pulled     4m22s                  kubelet            Successfully pulled image "crccheck/hello-world:latest" in 2.460558108s
  Normal   Pulled     3m51s (x5 over 6m6s)   kubelet            Container image "docker.io/hyhe/queue-39be6f1d08a095bd076a71d288d295b6@sha256:e78d4bfc0710ba603bb64aacb2e98aa26d4674a94b67d4633edf4e580725d3aa" already present on machine
  Warning  Failed     3m51s (x5 over 6m5s)   kubelet            Error: VM config for pod does not exist
  Warning  Failed     3m51s                  kubelet            Error: Failed to get/pull image: failed to resolve reference "ghcr.io/ease-lab/helloworld:var_workload": failed to do request: Head "https://ghcr.io/v2/ease-lab/helloworld/manifests/var_workload": dial tcp 13.234.166.55:443: i/o timeout
  Warning  Failed     99s (x5 over 6m6s)     kubelet            Error: Failed to get/pull image: failed to resolve reference "ghcr.io/ease-lab/helloworld:var_workload": failed to do request: Head "https://ghcr.io/v2/ease-lab/helloworld/manifests/var_workload": dial tcp 13.235.209.61:443: i/o timeout`

`Name:         private-reg
Namespace:    default
Priority:     0
Node:         awsum/192.168.122.60
Start Time:   Fri, 18 Mar 2022 18:02:17 +0000
Labels:       <none>
Annotations:  cni.projectcalico.org/podIP: 192.168.0.100/32
              cni.projectcalico.org/podIPs: 192.168.0.100/32
Status:       Running
IP:           192.168.0.100
IPs:
  IP:  192.168.0.100
Containers:
  private-reg-container:
    Container ID:   containerd://efaac6a9f22374c9ac15b3b743a14773bf4abe017e636e6c870d66ef3dd36ff9
    Image:          ghcr.io/ease-lab/helloworld:var_workload
    Image ID:       ghcr.io/ease-lab/helloworld@sha256:12dc6715ed1a8306f246ceaf7742c09e38a52a79d17421e4a50d7e0e09fdbc25
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Fri, 18 Mar 2022 18:02:19 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5nhpj (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-5nhpj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-5nhpj
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  12s   default-scheduler  Successfully assigned default/private-reg to awsum
  Normal  Pulled     11s   kubelet            Container image "ghcr.io/ease-lab/helloworld:var_workload" already present on machine
  Normal  Created    10s   kubelet            Created container private-reg-container
  Normal  Started    10s   kubelet            Started container private-reg-container`

**Comment by Pavi114** [comment]
I am able to pull the image but deployment still fails. I get an error while creating a container with firecracker.

```
time="2022-03-18T07:14:16.077111675Z" level=error msg="VM config for pod 51a63968cc242a9e2ba37fba2ea80f461ee36e28cf53eddd5494bb2def42ce35 does not exist"
time="2022-03-18T07:14:16.077120975Z" level=error error="VM config for pod does not exist"
time="2022-03-18T07:14:25.908931757Z" level=error msg="coordinator failed to start VM" error="failed to create the microVM in firecracker-containerd: rpc error: code = Unknown desc = failed to create VM: failed to start the VM: Put \"http://localhost/actions\": EOF" image="vhiveease/rnn_serving:var_workload" vmID=359
time="2022-03-18T07:14:25.909010757Z" level=error msg="failed to start VM" error="failed to create the microVM in firecracker-containerd: rpc error: code = Unknown desc = failed to create VM: failed to start the VM: Put \"http://localhost/actions\": EOF"
```

**Comment by catchabhisek** [comment]
I have seen that the default domain pods are going to error state:

> abhisek@awsum:~$ kubectl logs default-domain-2l4l7 -n knative-serving
W0320 06:44:07.317827       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"level":"fatal","ts":1647758657.4416451,"logger":"fallback.default-domain","caller":"default-domain/main.go:222","msg":"Error updating ConfigMap","error":"Internal error occurred: failed calling webhook \"config.webhook.istio.networking.internal.knative.dev\": Post \"https://net-istio-webhook.knative-serving.svc:443/config-validation?timeout=10s\": Not Found","stacktrace":"main.main\n\tknative.dev/serving/cmd/default-domain/main.go:222\nruntime.main\n\truntime/proc.go:255"}

As per few Github issues, the suggestions is to delete the validatingwebhookconfigurations, but i am not sure if it is to be done. Can anyone let me know their comments.

**Comment by catchabhisek** [comment]
I have removed the webhook, then the deployer script worked fine. However, the pod is getting deleted after the creation:

> Mar 21 08:00:48 awsum kubelet[16628]: E0321 08:00:48.661193   16628 remote_runtime.go:227] CreateContainer in sandbox "847d20a446e12eed1fe04ca12a4aed810bd95248bed2f7caf49461d5baacea29" from runtime service failed: rpc error: code = Unknown desc = Tuntap IOCTL TUNSETIFF failed [0], errno device or resource busy
Mar 21 08:00:48 awsum kubelet[16628]: E0321 08:00:48.661606   16628 kuberuntime_manager.go:829] container &Container{Name:user-container,Image:crccheck/hello-world:latest,Command:[],Args:[],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:user-port,HostPort:0,ContainerPort:50051,Protocol:TCP,HostIP:,},},Env:[]EnvVar{EnvVar{Name:GUEST_PORT,Value:50051,ValueFrom:nil,},EnvVar{Name:GUEST_IMAGE,Value:ghcr.io/ease-lab/helloworld:var_workload,ValueFrom:nil,},EnvVar{Name:PORT,Value:50051,ValueFrom:nil,},EnvVar{Name:K_REVISION,Value:helloworld-0-00001,ValueFrom:nil,},EnvVar{Name:K_CONFIGURATION,Value:helloworld-0,ValueFrom:nil,},EnvVar{Name:K_SERVICE,Value:helloworld-0,ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:default-token-c587j,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:&Lifecycle{PostStart:nil,PreStop:&Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/wait-for-drain,Port:{0 8022 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,},},TerminationMessagePath:/dev/termination-log,ImagePullPolicy:Always,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:FallbackToLogsOnError,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} start failed in pod helloworld-0-00001-deployment-7f9665d659-m8ljv_default(c826ac7c-8029-4d34-89f2-407fb2e0f336): CreateContainerError: Tuntap IOCTL TUNSETIFF failed [0], errno device or resource busy
Mar 21 08:00:48 awsum kubelet[16628]: E0321 08:00:48.666857   16628 remote_runtime.go:227] CreateContainer in sandbox "847d20a446e12eed1fe04ca12a4aed810bd95248bed2f7caf49461d5baacea29" from runtime service failed: rpc error: code = Unknown desc = VM config for pod does not exist
ar 21 08:00:48 awsum kubelet[16628]: E0321 08:00:48.667146   16628 pod_workers.go:191] Error syncing pod c826ac7c-8029-4d34-89f2-407fb2e0f336 ("helloworld-0-00001-deployment-7f9665d659-m8ljv_default(c826ac7c-8029-4d34-89f2-407fb2e0f336)"), skipping: [failed to "StartContainer" for "user-container" with CreateContainerError: "Tuntap IOCTL TUNSETIFF failed [0], errno device or resource busy", failed to "StartContainer" for "queue-proxy" with CreateContainerError: "VM config for pod does not exist"]

I have restarted my machine, ran the following scripts setup_firecracker_containerd.sh, setup_system.sh, create_devmapper.sh then i have started the containerd service, firecracker and vhive in screen. Can anyone please help me out with this.

**Comment by catchabhisek** [comment]
Restart of the machine, resolved the above issue. I have encountered that the pod gets deleted automatically, there is no error in vhive logs. Can anyone please help me with it:

> abhisek@awsum:~/vhive$ kubectl describe replicaset.apps/helloworld-0-00001-deployment-ddf67d98d
Name:           helloworld-0-00001-deployment-ddf67d98d
Namespace:      default
Selector:       pod-template-hash=ddf67d98d,serving.knative.dev/revisionUID=96a460e9-6e4f-40f0-b466-d84ff8bedb8d
Labels:         app=helloworld-0-00001
                pod-template-hash=ddf67d98d
                serving.knative.dev/configuration=helloworld-0
                serving.knative.dev/configurationGeneration=1
                serving.knative.dev/configurationUID=23b68415-8ed5-4a58-9eff-5dc16ee293b2
                serving.knative.dev/revision=helloworld-0-00001
                serving.knative.dev/revisionUID=96a460e9-6e4f-40f0-b466-d84ff8bedb8d
                serving.knative.dev/service=helloworld-0
                serving.knative.dev/serviceUID=33a3d47e-ea8e-411c-848c-fff5b85b655a
Annotations:    autoscaling.knative.dev/target: 1
                deployment.kubernetes.io/desired-replicas: 0
                deployment.kubernetes.io/max-replicas: 0
                deployment.kubernetes.io/revision: 1
                serving.knative.dev/creator: kubernetes-admin
Controlled By:  Deployment/helloworld-0-00001-deployment
Replicas:       0 current / 0 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:       app=helloworld-0-00001
                pod-template-hash=ddf67d98d
                serving.knative.dev/configuration=helloworld-0
                serving.knative.dev/configurationGeneration=1
                serving.knative.dev/configurationUID=23b68415-8ed5-4a58-9eff-5dc16ee293b2
                serving.knative.dev/revision=helloworld-0-00001
                serving.knative.dev/revisionUID=96a460e9-6e4f-40f0-b466-d84ff8bedb8d
                serving.knative.dev/service=helloworld-0
                serving.knative.dev/serviceUID=33a3d47e-ea8e-411c-848c-fff5b85b655a
  Annotations:  autoscaling.knative.dev/target: 1
                serving.knative.dev/creator: kubernetes-admin
  Containers:
   user-container:
    Image:      crccheck/hello-world:latest
    Port:       50051/TCP
    Host Port:  0/TCP
    Environment:
      GUEST_PORT:       50051
      GUEST_IMAGE:      ghcr.io/ease-lab/helloworld:var_workload
      PORT:             50051
      K_REVISION:       helloworld-0-00001
      K_CONFIGURATION:  helloworld-0
      K_SERVICE:        helloworld-0
    Mounts:             <none>
   queue-proxy:
    Image:       docker.io/hyhe/queue-39be6f1d08a095bd076a71d288d295b6@sha256:e78d4bfc0710ba603bb64aacb2e98aa26d4674a94b67d4633edf4e580725d3aa
    Ports:       8022/TCP, 9090/TCP, 9091/TCP, 8013/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP
    Requests:
      cpu:      25m
    Readiness:  http-get http://:8013/ delay=0s timeout=1s period=1s #success=1 #failure=3
    Environment:
      SERVING_NAMESPACE:                 default
      SERVING_SERVICE:                   helloworld-0
      SERVING_CONFIGURATION:             helloworld-0
      SERVING_REVISION:                  helloworld-0-00001
      QUEUE_SERVING_PORT:                8013
      CONTAINER_CONCURRENCY:             0
      REVISION_TIMEOUT_SECONDS:          300
      SERVING_POD:                        (v1:metadata.name)
      SERVING_POD_IP:                     (v1:status.podIP)
      SERVING_LOGGING_CONFIG:            
      SERVING_LOGGING_LEVEL:             
      SERVING_REQUEST_LOG_TEMPLATE:      {"httpRequest": {"requestMethod": "{{.Request.Method}}", "requestUrl": "{{js .Request.RequestURI}}", "requestSize": "{{.Request.ContentLength}}", "status": {{.Response.Code}}, "responseSize": "{{.Response.Size}}", "userAgent": "{{js .Request.UserAgent}}", "remoteIp": "{{js .Request.RemoteAddr}}", "serverIp": "{{.Revision.PodIP}}", "referer": "{{js .Request.Referer}}", "latency": "{{.Response.Latency}}s", "protocol": "{{.Request.Proto}}"}, "traceId": "{{index .Request.Header "X-B3-Traceid"}}"}
      SERVING_ENABLE_REQUEST_LOG:        false
      SERVING_REQUEST_METRICS_BACKEND:   prometheus
      TRACING_CONFIG_BACKEND:            none
      TRACING_CONFIG_ZIPKIN_ENDPOINT:    
      TRACING_CONFIG_DEBUG:              false
      TRACING_CONFIG_SAMPLE_RATE:        0.1
      USER_PORT:                         50051
      SYSTEM_NAMESPACE:                  knative-serving
      METRICS_DOMAIN:                    knative.dev/internal/serving
      SERVING_READINESS_PROBE:           {"tcpSocket":{"port":50051,"host":"127.0.0.1"},"successThreshold":1}
      ENABLE_PROFILING:                  false
      SERVING_ENABLE_PROBE_REQUEST_LOG:  false
      METRICS_COLLECTOR_ADDRESS:         
      CONCURRENCY_STATE_ENDPOINT:        
      CONCURRENCY_STATE_TOKEN_PATH:      /var/run/secrets/tokens/state-token
      HOST_IP:                            (v1:status.hostIP)
      ENABLE_HTTP2_AUTO_DETECTION:       false
    Mounts:                              <none>
  Volumes:                               <none>
Events:
  Type    Reason            Age    From                   Message
  ----    ------            ----   ----                   -------
  Normal  SuccessfulCreate  4m15s  replicaset-controller  Created pod: helloworld-0-00001-deployment-ddf67d98d-5nzhl
  Normal  SuccessfulDelete  3m8s   replicaset-controller  Deleted pod: helloworld-0-00001-deployment-ddf67d98d-5nzhl

**Comment by ustiugov** [comment]
hi @catchabhisek, sorry for the late response. can you please specify the host's specs, the steps to reproduce, and all necessary logs as specified in our GitHub Issue's template.

**Comment by ustiugov** [comment]
@catchabhisek is it still relevant? please close otherwise

**Comment by catchabhisek** [comment]
Hi, It seems there was an issue with proxy in the system. Resolved it.
