### ISSUE TITLE
Find only 3 script files in kind container ` vhiveease/vhive_dev_env`

### ISSUE THREAD

**Issue by CodingYuanLiu** [ease-lab/vhive#513]
Hi!!
I'm trying to use kind to deploy a vHive cluster. The reference is this [doc](https://github.com/ease-lab/vhive/blob/main/docs/developers_guide.md#deploying-single-node-container-environment).
After running the following commands, I find that there are only 3 files in the `script` dir:
``` bash
docker pull vhiveease/vhive_dev_env
kind create cluster --image vhiveease/vhive_dev_env
docker exec -it <container name> bash
cd script
ls
```
The result:
```
root@kind-control-plane:/scripts# ls
create_devmapper.sh  setup_cri_dev_env.sh  setup_system.sh
```
And there is no `/scripts/cluster/create_one_node_cluster.sh stock-only` that I can run

**Comment by ustiugov** [comment]
Shyam, I believe you update the images recently. Could you please take a look?

**Comment by ustiugov** [comment]
sorry for the delay, there has been quite a lot of travelling lately. We are going to check and fix it. In the meantime, please use `git clone` from inside kind.

**Comment by ustiugov** [comment]
@shyamjesal is it fixed in the updated runners?

**Comment by shyamjesal** [comment]
`create_one_node_cluster.sh` is not expected in the container as it is not required in container setup. When we run the tests we clone the repo inside the container and use the script from there.
