### ISSUE TITLE
Facing error while trying to use vhive as Go module

### ISSUE THREAD

**Issue by juno-kim** [ease-lab/vhive#515]
I'm trying to use vhive as a Go module in a separate Go program but facing the following error.

go: finding module for package github.com/ease-lab/vhive
go: downloading github.com/ease-lab/vhive v1.4.1
go: found github.com/ease-lab/vhive in github.com/ease-lab/vhive v1.4.1
go: github.com/ease-lab/vhive@v1.4.1 requires
        github.com/ease-lab/vhive/examples/protobuf/helloworld@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

Can anyone help with this?

**Comment by ustiugov** [comment]
Hi @juno-kim, I apologize for the delay. We haven't really developed vHive to be a Go module. For simplicity, we use `replace` pragmas in `go.mod` files in few places. 

Could you please describe your use case for using vHive as a module? We can discuss code improvements

**Comment by juno-kim** [comment]
Some of the vHive features seems useful so I just wanted to reuse them in a separate go program. I think I can work around this problem with replace pragmas as well. Thanks for the answer.

**Comment by ustiugov** [comment]
no problem, closing the issue.
